### PR TITLE
Chancing account and transaction to a map

### PR DESCRIPTION
**Pull request by rwobben**
Solve #18

### CODE REVIEW

**Comment by GetContented** [comment]
Looks good. I just wonder if we should make it AccountStore instead of Accounts, because Accounts is maybe too similar to Account? I'm a bit too finicky. It should be fine :)

**Comment by rwobben** [comment]
Also fine with me. 
New PR for this or let the change in the next PR which I think extracts the list functions out

**Comment by GetContented** [comment]
I don't mind. Probably just leave this as it is.

**Comment by rwobben** [comment]
Oops. I have changed it already.

**Comment by GetContented** [comment]
It's fine. Like I said, I don't mind. :)

**Comment by rwobben** [comment]
The last one is the right one. 
I think we refractored out all list functions. Most of them were already refractored out already

**Comment by GetContented** [comment]
The trouble with maybeAccountIdx is that Map doesn't have an index (unless you count the key?)

The semantics are actually slightly different...  If we look at this code:

    case maybeAccountIdx accountToDeposit accts of
      Nothing ->  do 
                 putStrLn "This account does not exist"
                 return accts  
      Just idx -> do 
                   putStrLn "Which amount do you want to deposit?"
                   amountToDeposit <- getLine
                   putStrLn "Could you give a description?"
                   descriptionDeposit <- getLine
                   let newAccounts = accountsAfterDeposit accts idx (read amountToDeposit::Amount) descriptionDeposit
                   return newAccounts

You're not actually interested in the index... which is an implementation detail. What you want to know here is "is this one in the accounts store"?

So I think this should be refactored to more clearly express that.

**Comment by rwobben** [comment]
oke, 

So refractor all the case statements to a function ?

**Comment by GetContented** [comment]
No, you still need the case statement, however the conditional expression uses a function application of something called maybeAccountIdx. Maps don't have indexes. They have keys. So, this would not make any sense.

We want to completely remove dependency on the type of thing that accounts is. Right now it's reliant on the fact that accounts has an index.

Do you see what I mean?

**Comment by GetContented** [comment]
As an example. If I want a gumball, and they're in a bucket, then I can say "get a gumball", or I can say "put your hand in, and pull out a gumball". Both are fine for buckets. However, one of these will still work with differently shaped containers, like for example a gumball dispensing machine. "Get a gumball" will still work, but "put your hand in and pull out a gumball" won't.

One is bound tightly to the container shape, the other is not. Do you see?

**Comment by rwobben** [comment]
I think I understand it.

But if we talking about this part : maybeAccountIdx accountToDeposit accts 

That is already a seperate function.

 maybeAccountIdx :: String -> AccountStore -> Maybe Int
 maybeAccountIdx s  = findIndex (isAccount s)

So the only thing I can image is another name.

**Comment by GetContented** [comment]
The problem is, it's getting an index. Maps don't have indexes.

What does that piece *actually* mean? If it *has* to be an index, then it's impossible to change our code to use Map.

**Comment by GetContented** [comment]
We actually want to change the type to be a Bool, I think... because we're saying

"Hey, Haskell, is there an Account named this already?"

The answer is "yes" or "no", which in Haskell, is True or False, and these are of type Bool.

**Comment by rwobben** [comment]
oke, 

but if we change it to a boolean we also have to rewrite the findIndex part. 
I thought that will be the second part. Chancing code so it works with a map

**Comment by rwobben** [comment]
I think we do not understand each other. 
Can you give a example what you mean?

**Comment by GetContented** [comment]
Actually it just involves moving the part that relies on an index into the code that uses it.

Introducing a Bool has nothing to do with Map.

**Comment by rwobben** [comment]
sorry, I still do not see what you mean

**Comment by GetContented** [comment]
Ok. Let's try something else. Maybe you could explain to me what we're doing?

**Comment by rwobben** [comment]
oke, we try to take out all the things that depends on list. 

We have this part : 

   case maybeAccountIdx accountToDeposit accts of

which return a Maybe Integer or a Nothing. 

The function looks like this : 

    maybeAccountIdx :: String -> AccountStore -> Maybe Int
    maybeAccountIdx s  = findIndex (isAccount s)

But maps do not have a index , this has to be changed so it returns a Boolean. 

So in my opionion we could do this  but then we have to find a function that does the same as findIndex but returns a bool.  Then we could rerwite the case statement.

**Comment by GetContented** [comment]
But we're using idx in the Just match of the case, so how will that work?

**Comment by rwobben** [comment]
We have to find another way to pull the right account out of the Accounts

**Comment by GetContented** [comment]
What if we wrote a new function called accountsAfterDeposit' and made it almost identical to accountsAfterDeposit, except instead of idx :: Int, it took an accountName :: String, and it did the look up using maybeAccountIdx itself, using a case. If it's Nothing, return accts, but if it's not, do the deposit and return that.

Then, we could change this line in doDepositAccounts:

    let newAccounts = accountsAfterDeposit accts idx (read amountToDeposit::Amount) descriptionDeposit

... so that instead of calling accountsAfterDeposit with idx, we call our new accountsAfterDeposit' function with the accountName.

Once we'd made THAT change, we wouldn't be relying on the idx anymore, so we could then work on a function that returns a Bool to replace our case in our main doDepositAccounts case statement.

**Comment by rwobben** [comment]
Oke, I think I see what you mean.
We could rewrite and rename the maybeAccountidx so it providing the name of the account.

**Comment by GetContented** [comment]
What I mean is we're using maybeAccountIdx for two things;

1. To check if there is an account at all (Yes/No values are usually best kept as a Bool, but we're using Nothing / Just instead here)
1. To get an index out that our accountsAfterDeposit uses later.

We want to take the idx out of the doDepositAccounts entirely, because this is keeping us from refactoring to use a Map.

To do that, we need to do what I said above, and then, to write a new function that returns a Bool if the account is in the accounts list, and use that for the case conditional.

We can do all of this without causing ourselves any errors or problems.

**Comment by rwobben** [comment]
Oke, 

Then I was on the wrong track with this solution ; 

    doDepositAccounts :: AccountStore -> IO AccountStore
    doDepositAccounts accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      case maybeAccountIdx accountToDeposit accts of
        Nothing ->  do 
                   putStrLn "This account does not exist"
                   return accts  
        Just idx -> do 
                     putStrLn "Which amount do you want to deposit?"
                     amountToDeposit <- getLine
                     putStrLn "Could you give a description?"
                     descriptionDeposit <- getLine
                     let newAccounts = accountsAfterDeposit accts idx (read amountToDeposit::Amount) descriptionDeposit
                     return newAccounts

    maybeAccountIdx :: String -> AccountStore -> Account
    maybeAccountIdx s accts = accts !! findIndex (isAccount s)

    accountsAfterDeposit :: AccountStore -> Account -> Amount -> Description -> AccountStore
    accountsAfterDeposit accts account amountToDeposit descriptionForDeposit = (take idx accts) ++ [depositedAccount] ++ drop (idx + 1) accts
      where depositedAccount = deposit amountToDeposit  descriptionForDeposit  account
        
    isAccount :: String -> Account -> Bool
    isAccount name acct = accountName acct == name

**Comment by GetContented** [comment]
Yes.

Also, I think there are a lot of bugs in that.

    maybeAccountIdx :: String -> AccountStore -> Account
    maybeAccountIdx s accts = accts !! findIndex (isAccount s)

For this, function application is highest priority, so !! will evaluate first, and try to apply to accts and findIndex, which won't work: accts !! findIndex (isAccount s)

Even if you put parenthesis around to make it work like this accts !! (findIndex (isAcount s)) then you'll have problems because the types are wrong. (!!) takes a list, and an Int, but findIndex returns a Maybe Int, not an Int.

**Comment by GetContented** [comment]
I'm trying to get you to write software in such a way that you cannot get bugs.

**Comment by GetContented** [comment]
I wanted YOU to do this, but I guess it's somehow too difficult maybe? I'm not sure why this is so difficult.

**Comment by GetContented** [comment]
Let's look...

    doDepositAccounts :: AccountStore -> IO AccountStore
    doDepositAccounts accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      case maybeAccountIdx accountToDeposit accts of
        Nothing ->  do 
                   putStrLn "This account does not exist"
                   return accts  
        Just idx -> do 
                     putStrLn "Which amount do you want to deposit?"
                     amountToDeposit <- getLine
                     putStrLn "Could you give a description?"
                     descriptionDeposit <- getLine
                     let newAccounts = accountsAfterDeposit accts idx (read amountToDeposit::Amount) descriptionDeposit
                     return newAccounts

    maybeAccountIdx :: String -> AccountStore -> Maybe Int
    maybeAccountIdx s  = findIndex (isAccount s)

    accountsAfterDeposit :: AccountStore -> Int -> Amount -> Description -> AccountStore
    accountsAfterDeposit accts idx amountToDeposit descriptionForDeposit = (take idx accts) ++ [depositedAccount] ++ drop (idx + 1) accts
      where depositedAccount = deposit amountToDeposit  descriptionForDeposit  (accts!!idx)

Ok, so we want to get rid of idx form doDepositAccounts.

First thing to do is get rid of it from accountsAfterDeposit. To do that, write a new function that takes a String rather than an idx :: Int:

    accountsAfterDeposit' :: AccountStore -> String -> Amount -> Description -> AccountStore
    accountsAfterDeposit' accts accountName amountToDeposit descriptionForDeposit = 
      case maybeAccountIdx accountName accts of 
        Nothing  -> accts
        Just idx -> let depositedAccount = deposit amountToDeposit  descriptionForDeposit (accts!!idx)
                    in (take idx accts) ++ [depositedAccount] ++ drop (idx + 1) accts

Ok, now we can change our let in doDepositAccounts to use this new function:

    doDepositAccounts :: AccountStore -> IO AccountStore
    doDepositAccounts accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      case maybeAccountIdx accountToDeposit accts of
        Nothing ->  do 
                   putStrLn "This account does not exist"
                   return accts  
        Just idx -> do 
                     putStrLn "Which amount do you want to deposit?"
                     amountToDeposit <- getLine
                     putStrLn "Could you give a description?"
                     descriptionDeposit <- getLine
                     let newAccounts = accountsAfterDeposit' accts accountToDeposit (read amountToDeposit::Amount) descriptionDeposit
                     return newAccounts

Ok... see how we just got rid of one reference to idx? Now for the other one... to do that, we need a function that checks if the account is there at all...

    doesAccountExistInAccounts :: String -> AccountStore -> Bool
    doesAccountExistInAccounts accName accts = any (\x -> accountName x == accName) accts

Then we can refactor the case statement in doDepositAccounts to a simple if statement rather than a case, to remove the last occurrence of idx:

    doDepositAccounts :: AccountStore -> IO AccountStore
    doDepositAccounts accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      if doesAccountExistInAccounts accountToDeposit accts
      then do 
         putStrLn "This account does not exist"
         return accts  
      else do 
         putStrLn "Which amount do you want to deposit?"
         amountToDeposit <- getLine
         putStrLn "Could you give a description?"
         descriptionDeposit <- getLine
         let newAccounts = accountsAfterDeposit' accts accountToDeposit (read amountToDeposit::Amount) descriptionDeposit
         return newAccounts

**Comment by GetContented** [comment]
Anyway, I wrote that for you, of course. I hope you read it, because I know all this stuff myself. It's not for me. It's so you can learn.

Also, I haven't checked the code. Don't just copy and paste and assume it works. Really try to understand what I'm doing and why I'm doing it, and then do it yourself.

**Comment by rwobben** [comment]
I am reading this and studying. I assumed that we got rid of idx at all. 
But I understand what you are doing.

**Comment by GetContented** [comment]
Yeah, by doing this we've now "sectioned off" all our use of list-based functions  around the account store. So, we can just have a few small functions to rewrite to work with Maps. Once we've written them, we can quickly and easily change the types and function references. It's easier to shift because they're not interdependent on List.

If we didn't do what I just outlined, it'd be a massive pain to refactor the doDepositAccounts function. This way, it'll be a piece of cake.

**Comment by rwobben** [comment]
Oke, 

I think the first one is this one : 

    addAccount :: Account -> AccountStore -> AccountStore
    addAccount newAcct accounts = newAcct : accounts

As I understand the docs from map right we can make it work like this ; 

    addAccount :: Account -> AccountStore -> AccountStore
    addAccount newAcct accounts = insert newAcct accounts 

But I wonder do we not need to make a empty map with map.empty ?

**Comment by rwobben** [comment]
It could work when we figure out the types. 
Must be change the type Account sentence to make this work ?

**Comment by rwobben** [comment]
Still here and wants to help me ?

**Comment by GetContented** [comment]
Sorry I didn't get any notifications until now.

**Comment by GetContented** [comment]
I don't think we're up to doing this yet, are we? I can't tell - did you finish putting all the changes I made in that would factor out List and whatnot? It'd be good to see the code as it is.

**Comment by GetContented** [comment]
Don't rewrite functions, because we don't want to break our existing software. We want to write some NEW type-correct functions that we *will* use to replace our existing list-ones, but not yet. Otherwise we'll have to do a huge amount of changes all at once, and it'll break a lot and you'll spend a lot of time fixing things and you'll probably give up.

**Comment by rwobben** [comment]
All the old changes are now in a PR

**Comment by GetContented** [comment]
I can't see it.

**Comment by rwobben** [comment]
Wierd,. I also not. 
I can see it when I look at commits.

**Comment by GetContented** [comment]
Ok yeah, it's there now.

**Comment by GetContented** [comment]
Anyway let's look at the type of Map. It has two type variables k, and a. Map k a.
Map is a data structure. It is for connecting values to keys. I'm assuming we want to connect Account to account names.

so let's create a type synonym 
    
    type Accounts' = Map String Account

and then we can begin to create map-versions of all of our list-related functions.

For example:

    deleteAccount :: String -> Accounts -> Accounts
    deleteAccount s  = filter notNamed
      where notNamed acct = accountName acct /= s                             

This function removes an account named a certain thing. We can use the delete function from Data.Map 

    deleteAccount' :: String -> Accounts' -> Accounts'
    deleteAccount' s accts = delete s accts

**Comment by rwobben** [comment]
Oke, 

I did do that and delete now looks like this : 

    doDeleteAccounts2 :: AccountStore -> IO AccountStore
    doDeleteAccounts2 accounts = do
      putStrLn "Please enter an account name to delete?"
      acctName <- getLine
      let newAccounts = deleteAccount acctName accounts
      return newAccounts
                              
    deleteAccount s  = filter notNamed
      where notNamed acct = accountName acct /= s 
  
    deleteAccount' :: String -> AccountStore' -> AccountStore'
    deleteAccount' s accts = delete s accts

And see these type errors ; 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:73:26:
        Couldn't match type ‘[String]’ with ‘Map String Account’
        Expected type: AccountStore'
          Actual type: [String]
        In the expression: delete s accts
        In an equation for ‘deleteAccount'’:
            deleteAccount' s accts = delete s accts

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:73:35:
        Couldn't match type ‘Map String Account’ with ‘[String]’
       Expected type: [String]
         Actual type: AccountStore'
        In the second argument of ‘delete’, namely ‘accts’
        In the expression: delete s accts

**Comment by GetContented** [comment]
You're using unqualified imports, and you've dot Data.List as well as Data.Map and both of them have a delete function.

**Comment by GetContented** [comment]
I suggest you don't just use import Data.Map but rather import qualified Data.Map as M, then change type Accounts' = Map String Account to be type Accounts' = M.Map String Account and change delete to M.delete

**Comment by rwobben** [comment]
Thanks, 

I found out that myself.
My code looks now like this :  http://lpaste.net/148833

I think the next problem is to change doDeleteAccounts so it uses deleteAccount'  instead of deleteAccount. Right ?

**Comment by GetContented** [comment]
No, if you do that, it'll break your code.

**Comment by GetContented** [comment]
Oh sorry I should have said type AccountsStore' = Map.Map String Account not type Accounts' =...

**Comment by GetContented** [comment]
Sorry I meant AccountStore. It's hard to keep up.

**Comment by GetContented** [comment]
You want to write new versions of all the rest of the code that uses AccountStore as a list.

Then, once this is done, in one step, you can:
  - comment out the old ones
  - comment out the old type 
  - rename the AccountStore' type to AccountStore
  - rename all the functions that have ' on the end to remove the ' (so they become the ones all the functions are referring to.

And that's it.

**Comment by rwobben** [comment]
as a list ? 

I thought AccountStore is a map. 

I finisched "rewriting" doDeleteAccounts and it compiles :) 

It looks like this : 

doDeleteAccounts' :: AccountStore' -> IO AccountStore'
doDeleteAccounts' accounts = do
  putStrLn "Please enter an account name to delete?"
  acctName <- getLine
  let newAccounts = deleteAccount' acctName accounts
  return newAccounts

**Comment by rwobben** [comment]
So if it's oke with you, I can delete the old ones and one part is ready :)

**Comment by GetContented** [comment]
Hehe. It's more work, but sure you do this however you like.

**Comment by rwobben** [comment]
I can leave the old list versions of deleting a account if you want that. 
But is the code right and can I busy with add a account functions ?

**Comment by GetContented** [comment]
Yep.

**Comment by rwobben** [comment]
oke, 

I added this function : 

    addAccount' :: Account -> AccountStore' -> AccountStore'
    addAccount' newAcct accounts = Map.insert newAcct accounts

and I see these error messages : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:60:32:
        Couldn't match type ‘Map Account AccountStore'
                             -> Map Account AccountStore'’
                       with ‘Map String Account’
        Expected type: AccountStore'
         Actual type: Map Account AccountStore'
                   -> Map Account AccountStore'
       Probable cause: ‘Map.insert’ is applied to too few arguments

So I schould change AccountStore' to Map Account Accountstore'    ?
 
    In the expression: Map.insert newAcct accounts
    In an equation for ‘addAccount'’:
        addAccount' newAcct accounts = Map.insert newAcct accounts

**Comment by GetContented** [comment]
No, the AccountStore' type is correct. Your function is incorrect.

What is Map.insert doing? What's its type?  What do you want it to do in that function?

**Comment by GetContented** [comment]
Look at the types, and match them up. This is the type for Map.insert:

    insert :: Ord k => k -> a -> Map k a -> Map k a

Can you read that type? How many arguments does it have, and what types are they, given our Map k a is a Map String Account (that is, k = String, a = Account)

**Comment by rwobben** [comment]
I think three

Ord K => k  is one 
a is one 
map k a  is one

**Comment by GetContented** [comment]
Yeah, that's right. Now look at your function:

    addAccount' :: Account -> AccountStore' -> AccountStore'
    addAccount' newAcct accounts = Map.insert newAcct accounts

Are you applying three arguments to Map.insert? It looks like there are only two to me. You have Map.insert, then an Account, then a Map. You're missing one... right?

**Comment by GetContented** [comment]
The one you're missing is a String. But what String?

What is this map mapping from to? We know it's mapping from String to Account, but what data are we hoping to store in that String type? What information do we want to store Account data under? What data do we want to look it up under?

I assumed it was the name of the account.

**Comment by rwobben** [comment]
No, we wanted to store a Account in the Store. 
So insert is I think the wrong way. 
Back to the docs

**Comment by rwobben** [comment]
Oke

So the name can be the key so the String 
the Accountbalance must then be the value. 

So we have to find another way to store the transactions.
As far as I know Map works with key/value

**Comment by rwobben** [comment]
I think we could better do something like this : 

( accountname, Account)

**Comment by GetContented** [comment]
I'm not sure what you're not understanding here.

Map lets you store many values each against a key. I was assuming you'd want to store an Account under their account name so you could look them up by that.

Meaning the key is the account name, and the whole account is the value.

A map is a collection data type, not a single data item. It's akin to [(String, Account)], but it's much more efficient than that because of the way it works internally.

**Comment by GetContented** [comment]
I'm pretty sure Map *is* the right thing to store accounts under given that we want to store and look them up based on their account name. This is a perfect use-case for Map.

**Comment by rwobben** [comment]
oke, got addAccount working with : 

    makeAccount :: String -> Amount -> Account
    makeAccount n a = Account {accountName = n, accountBalance = a, accountTransaction = []}


    doCreateAccounts :: AccountStore' -> IO AccountStore'
    doCreateAccounts accounts = do
      putStrLn "Enter new account name"
      newName <- getLine
      putStrLn "Enter new account balance"
      balStr <- getLine
      let newBal      = read balStr :: Integer
          newAcct     = makeAccount newName newBal
          newAccounts = addAccount newName newAcct accounts
      putStrLn $ "Account " ++ newName ++ " made with balance " ++ show newBal ++ "."
      return newAccounts

    addAccount :: String -> Account -> AccountStore' -> AccountStore'
    addAccount s newAcct accounts = Map.insert s newAcct accounts

Only a lot of type errors on main,hs

**Comment by rwobben** [comment]
Now the most difficult one. the deposit function. 

I think we can use Lookup to look if a account exist.

**Comment by rwobben** [comment]
oke, 
Almost working 

    doesAccountExistInAccounts' :: String -> AccountStore' -> Maybe Account 
    doesAccountExistInAccounts' accName accts = Map.lookup accName accts

    doDepositAccounts' :: AccountStore' -> IO AccountStore'
    doDepositAccounts' accts = do
       putStrLn "To which account do you want to deposit? "
       accountToDeposit <- getLine
      case doesAccountExistInAccounts' accountToDeposit accts of 
        Nothing -> do 
                           putStrLn "This account does not exist"
                           return accts  
        Just name -> do
                                 putStrLn "Which amount do you want to deposit?"
                                amountToDeposit <- getLine
                                putStrLn "Could you give a description?"
                                descriptionDeposit <- getLine
                               return accts

Tomorrow I try to find out which function does update a account.

**Comment by rwobben** [comment]
Nothing on the televison.

Im this far with the make a transition part 

    doesAccountExistInAccounts' :: String -> AccountStore' -> Maybe Account 
    doesAccountExistInAccounts' accName accts = Map.lookup accName accts

    doDepositAccounts' :: AccountStore' -> IO AccountStore'
    doDepositAccounts' accts = do
      putStrLn "To which account do you want to deposit? "
     accountToDeposit <- getLine
      case doesAccountExistInAccounts' accountToDeposit accts of 
        Nothing -> do 
                     putStrLn "This account does not exist"
                      return accts  
        Just name -> do
                      putStrLn "Which amount do you want to deposit?"
                      amountToDeposit <- getLine
                       putStrLn "Could you give a description?"
                      descriptionDeposit <- getLine
                      let depositedAccount = addTransaction name (read amountToDeposit::Integer) accts
                      return accts

    addTransaction :: Account -> Integer -> AccountStore' -> AccountStore'
    addTransaction account amount accts  = accts

it compiles well  but Im have doubts about this 
Am I stil on the right track.
If i am , then I will try to inplement the adjust function tomorrow morning (European time)

**Comment by GetContented** [comment]
In this function, why don't you just get the accountName from the account you pass in? That's what I was hoping you'd notice yourself.

   addAccount :: String -> Account -> AccountStore' -> AccountStore'
   addAccount s newAcct accounts = Map.insert s newAcct accounts

Why not just

    addAccount :: Account -> AccountStore' -> AccountStore'
    addAccount s newAcct accounts = Map.insert (accountName newAcct) newAcct accounts

**Comment by GetContented** [comment]
I'm a bit curious why you're using something called addTransaction there? Don't you want to actually do something like depositInAccount ?

**Comment by rwobben** [comment]
Thanks for the feedback. 
I see another "errror"  At this moment , I do not use the deposit function to make a new account. 

What I wanted to do in addTransaction was to make a new AccountStore with the updated account. 
I can give it a other name. 

I think I can solve this the same way as we did here : 

    let depositedAccount = deposit amountToDeposit  descriptionForDeposit (accts!!idx)
                    in (take idx accts) ++ [depositedAccount] ++ drop (idx + 1) accts

The only thing I have to figure out which function I need. My initial idea was to use adjust but the amount is already changed.

**Comment by rwobben** [comment]
I doubt between insert and update. But I also think that update is clearer what the functions do

**Comment by GetContented** [comment]
Yeah, something this won't work:

    let depositedAccount = deposit amountToDeposit  descriptionForDeposit (accts!!idx)
                in (take idx accts) ++ [depositedAccount] ++ drop (idx + 1) accts

because it's using lists.

You're on the right track with insert or update. Update takes an updating function, whereas insert is just a straight up replacement if there's an item with that key already in the Map.

**Comment by GetContented** [comment]
You should test these out yourself at the command line, maybe... : 

    > insert 1 309 $ fromList [(1,2),(3,4)]
    fromList [(1,309),(3,4)]

but `adjust` might be more what you want...:

    > adjust (*5) 3 $ fromList [(1,2),(3,4)]
    fromList [(1,2),(3,20)]

**Comment by rwobben** [comment]
I looked at adjust but deposit does already the adjusting.

I have now this : 

    doDepositAccounts' :: AccountStore' -> IO AccountStore'
    doDepositAccounts' accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
     case doesAccountExistInAccounts' accountToDeposit accts of 
        Nothing -> do 
                     putStrLn "This account does not exist"
                     return accts  
        Just name -> do
                      putStrLn "Which amount do you want to deposit?"
                      amountToDeposit <- getLine
                      putStrLn "Could you give a description?"
                      descriptionDeposit <- getLine
                      let newAccount = (deposit amountToDeposit  descriptionForDeposit name)
                      in updateAccountInStore newAccount accts
                      return newAccount


but I get a parse error on the let in line.
Can you give a hint where the bug is.

**Comment by GetContented** [comment]
adjust would actually be perfect. It takes a function that does something to a value (deposit), and a key (that is how it finds which value to run the function on), a map, and gives you a new map with the adjusted value in it. That's exactly what we want.

**Comment by GetContented** [comment]
You're getting a parse error because the let-in is a single expression that results in a value that is not in IO. In do blocks (of type IO), every expression must be using etiher <- or let (without in), or evaluate to an IO value. This does none of those things. It's just a single expression that reselts in an Accounts, I think.

Also, the return function is wrapping a single account in IO, and the return value of doDepositAccounts' needs to be IO [Account], not IO Account.

That's a hint. :)

**Comment by rwobben** [comment]
Oke, 

I tried it with adjust 

    doDepositAccounts' :: AccountStore' -> IO AccountStore'
    doDepositAccounts' accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      case doesAccountExistInAccounts' accountToDeposit accts of 
        Nothing -> do 
                     putStrLn "This account does not exist"
                     return accts  
        Just name -> do
                      putStrLn "Which amount do you want to deposit?"
                      amountToDeposit <- getLine
                      putStrLn "Could you give a description?"
                      descriptionDeposit <- getLine
                      let newAccount = updateAccountInStore (read amountToDeposit::Integer) descriptionDeposit  newAccount accts
                      return newAccount
                
    updateAccountInStore ::  Integer -> String ->Account -> AccountStore' -> AccountStore'
    updateAccountInStore amount description acct accts = Map.adjust (deposit amount description acct ) (accountName acct) accts

But now a lot of type errors. 
I think I loose track of things again. 

I know that adjust has a type of this : 

   adjust :: Ord k => (a -> a) -> k -> Map k a -> Map k a

so it takes a account  , puts it into a function which returns a account. 
I have done that with the deposit function 
Then it takes the map which is accts here. 
and puts out a new map. 

Where am I wrong ? 

Roelof

**Comment by GetContented** [comment]
There might be a typemismatch if this function application doesn't evaluate to a Maybe String: doesAccountExistInAccounts' accountToDeposit accts

Next thing is you're returning a value of type IO Account from the "Just" part of your case expression. This is wrong, as it doesn't match the type of the entire function, which needs to return something of type IO AccountStore' 

Next, the adjust function takes 3 arguments. The first is a function, but you're passing it a value (deposit amount description acct). To make it a function, leave off acct: (deposit amount description).

**Comment by GetContented** [comment]
Also, this doesn't make any sense:

    let newAccount = updateAccountInStore (read amountToDeposit::Integer) descriptionDeposit  newAccount accts

newAccount doesn't exist at the point you're applying updateAccountInStore to it.

You don't *have* the account at this point, so what you actually want to do is change updateAccountInStore so it takes the account's name, not an account. Then you can adjust your let and return to:

        let newAccounts = updateAccountInStore (read amountToDeposit::Integer) descriptionDeposit  accountToDeposit accts
        return newAccounts

**Comment by GetContented** [comment]
... but this can be reduced to:

return $ updateAccountInStore (read amountToDeposit::Integer) descriptionDeposit  accountToDeposit accts

... because you don't need a let expression if you're only assigning one variable and then wrapping it in return.

**Comment by rwobben** [comment]
Bummer : 

Now a lot of type errors on the addAccount part which compiles good yesterday.

    doCreateAccounts' :: AccountStore' -> IO AccountStore'
    doCreateAccounts' accounts = do
      putStrLn "Enter new account name"
      newName <- getLine
      putStrLn "Enter new account balance"
      balStr <- getLine
      let newBal      = read balStr :: Integer
          newAcct     = makeAccount newName newBal
          newAccounts = addAccount' newName newAcct accounts
      putStrLn $ "Account " ++ newName ++ " made with balance " ++ show newBal ++ "."
      return newAccounts

    addAccount' :: Account -> AccountStore' -> AccountStore'
    addAccount' s newAcct accounts = Map.insert (accountName newAcct) newAcct accounts


Here are a few : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:70:41:
        Couldn't match type ‘Account’ with ‘Map String Account’
        Expected type: AccountStore'
         Actual type: Account
        In the second argument of ‘addAccount'’, namely ‘newAcct’
        In the expression: addAccount' newName newAcct accounts

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:75:1:
        Couldn't match expected type ‘Map String AccountStore'
                                      -> Map String AccountStore'’
                    with actual type ‘Map String Account’
        The equation(s) for ‘addAccount'’ have three arguments,
        but its type ‘Account -> AccountStore' -> AccountStore'’
        has only two

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:75:58:
        Couldn't match type ‘Map String Account’ with ‘Account’
        Expected type: Account
          Actual type: AccountStore'
        In the first argument of ‘accountName’, namely ‘newAcct’
        In the first argument of ‘Map.insert’, namely
          ‘(accountName newAcct)’
Failed, modules loaded: none.

**Comment by GetContented** [comment]
This is not correct. Count the number of arguments in the function compared to in the type signature.

Come on, you can do this yourself, can't you?

    addAccount' :: Account -> AccountStore' -> AccountStore'
    addAccount' s newAcct accounts = Map.insert (accountName newAcct) newAcct accounts

it should not have an s in there

**Comment by rwobben** [comment]
Everything compiles well now.
Untested code : http://lpaste.net/148858

I think I can test this in ghci

**Comment by rwobben** [comment]
Tested it with 1 account and everything seems to work well. 
If you are also happy . I could delete the list functions and merge it into the make-a-main branch

**Comment by GetContented** [comment]
I'm happy if you are. Once you've cleaned it up I'll have a bit of a look if you like.

**Comment by rwobben** [comment]
Im happy.  But if you have a look if everything is still good then we can close this one and merge into the make-main branch and work on the last challenges there.

**Comment by GetContented** [comment]
Ok... deleteAccount can be refactored to

    deleteAccount = Map.delete

you can refactor these two functions to this:

    doesAccountExistInAccounts :: String -> AccountStore -> Bool
    doesAccountExistInAccounts accName accts = (Map.lookup accName accts) /= Nothing

    doDepositAccounts :: AccountStore -> IO AccountStore
    doDepositAccounts accts = do
      putStrLn "To which account do you want to deposit? "
      accountToDeposit <- getLine
      case doesAccountExistInAccounts accountToDeposit accts of 
      if doesAccountExistInAccounts accountToDeposit accts
      then do 
        putStrLn "This account does not exist"
        return accts  
      else do
        putStrLn "Which amount do you want to deposit?"
        amountToDeposit <- getLine
        putStrLn "Could you give a description?"
        descriptionDeposit <- getLine
        return $ updateAccountInStore (read amountToDeposit::Integer) descriptionDeposit accountToDeposit accts

They're just a lot simpler, is all.

**Comment by GetContented** [comment]
Also "updateAccountInStore" is a misleading name when it is only doing deposits. It should be depositToAccountInStore or something like that.

**Comment by rwobben** [comment]
so, changed.
I will merge this one and make-a-main branch right now.

**Pull request merged**
