### PR TITLE
adding and deleting accounts

### PR DESCRIPTION
**Pull request by rwobben**
A part of the making a main function.

### CODE REVIEW

**Comment by GetContented** [comment]
Cool. I'm not sure we need both the index AND the filter one for deleteAccounts, and I think the filter one is a lot smaller, which is probably better, but that's fine for now - we can clean it up later, I guess.

**Comment by rwobben** [comment]
I like to hold both because I think we can use the index one for a validation for input so we can take care that a account is not entered two times. 

But I find it no problem to use the filter one for real and make the index one a comment or something else.

**Comment by GetContented** [comment]
Sure. Doesn't bother me either way... so long as you don't come back to it later and say "What on earth is this here for?" :)

**Comment by rwobben** [comment]
Agreed

**Pull request merged**
