### PR TITLE
All transactions of a account can be printed

### PR DESCRIPTION
**Pull request by rwobben**
All the transaction can be printed as we wish :)

### CODE REVIEW

**Comment by rwobben** [comment]
What do you think about this code : http://lpaste.net/151089
Enough "refractored" so the IO is out of functions.

**Comment by GetContented** [comment]
It's much nicer code than previously.

this code:

    validAccount  accounts =
      do 
        answer <- prompt "From which account do you want to withdraw: "
        return answer 

you can reduce to:

    validAccount  accounts = prompt "From which account do you want to withdraw: "

...because of the function's return type (I don't mean the return function). You don't need a do block if it just does the same thing as the expression it wraps or unwraps.

However, I don't understand why `validAccount` is taking the `accounts` argument? It doesn't use it at all. Isn't it supposed to validate the account as being present or something?

**Comment by rwobben** [comment]
No ,it a error of me.

**Comment by GetContented** [comment]
Ok. Cool then. Mostly looks pretty good.

**Comment by rwobben** [comment]
Mostly ?? What can I change more. 
I have asked people on irc and they told me it's allright and they have no points that I can improve,

**Comment by GetContented** [comment]
Nothing much really. 

I don't think this line needs parentheses:

    if (doesAccountExistInAccounts newAccountName accounts)


This should have an s on the end:

    "Account already exist"


Apart from that, all good :)

**Comment by rwobben** [comment]
parenthenses are already deleted. Hlint found that one.
The other one I will change

**Comment by GetContented** [comment]
On subsequent reflection, the reason this feels like perhaps there needs to be more stuff refactored out is that there are thing in here which will most likely be shared across other parts of your project (like the function that creates an action to print something on the screen).

If you're just talking about within this file, though, then you're golden :) Really well done.

**Comment by rwobben** [comment]
Thanks, 

That was the reason for refractoring. Making smaller functions and the parts that are used in other places make new functions so they can be reused.

**Comment by GetContented** [comment]
It's called refactoring, not refractoring. (Small nit-pick).

Yeah, when you make a function that can be reused across many files, it's good to put it into a general place, if possible. I'm sure you know this.

**Comment by GetContented** [comment]
You can merge this now I think.

**Comment by rwobben** [comment]
Yep, you are right

**Pull request merged**
